# Generated by Django 2.1.7 on 2019-12-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ahmedabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('total_spaces', models.CharField(max_length=5)),
                ('vacancy', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gandhinagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('total_spaces', models.CharField(max_length=5)),
                ('vacancy', models.CharField(max_length=5)),
            ],
        ),
    ]
