# Generated by Django 3.0.4 on 2020-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='City',
        ),
        migrations.AddField(
            model_name='contact',
            name='Contents',
            field=models.TextField(default='Please enter your message here', max_length=200),
        ),
    ]
