# Generated by Django 3.0.4 on 2020-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_sensor', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
