# Generated by Django 3.0.4 on 2020-05-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_sensor', '0005_auto_20200529_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
