# Generated by Django 3.0.4 on 2020-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_sensor', '0007_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Email',
        ),
        migrations.AddField(
            model_name='booking',
            name='response',
            field=models.CharField(default='null', max_length=25),
        ),
    ]
